// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for rental-app-9e26c project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClqExNN1Xrto3J87Wdf72zpoTbuW9QZ1Y',
    appId: '1:350979911369:web:xxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '350979911369',
    projectId: 'rental-app-9e26c',
    authDomain: 'rental-app-9e26c.firebaseapp.com',
    storageBucket: 'rental-app-9e26c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClqExNN1Xrto3J87Wdf72zpoTbuW9QZ1Y',
    appId: '1:350979911369:android:aeb0901da2d63ecf082718',
    messagingSenderId: '350979911369',
    projectId: 'rental-app-9e26c',
    storageBucket: 'rental-app-9e26c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClqExNN1Xrto3J87Wdf72zpoTbuW9QZ1Y',
    appId: '1:350979911369:ios:fc3dcd6e73e36701082718',
    messagingSenderId: '350979911369',
    projectId: 'rental-app-9e26c',
    storageBucket: 'rental-app-9e26c.firebasestorage.app',
    iosClientId: '350979911369-o8tbrb5itjm4c9dskac0oj05bj50qm2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.goRentFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClqExNN1Xrto3J87Wdf72zpoTbuW9QZ1Y',
    appId: '1:350979911369:ios:fc3dcd6e73e36701082718',
    messagingSenderId: '350979911369',
    projectId: 'rental-app-9e26c',
    storageBucket: 'rental-app-9e26c.firebasestorage.app',
    iosClientId: '350979911369-o8tbrb5itjm4c9dskac0oj05bj50qm2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.goRentFrontend',
  );
} 